### ISSUE TITLE
Where can I find apk's?

### ISSUE THREAD

**Issue by benwaffle** [wakarimasenco/ChanExplorer#1]

**Comment by miyachan** [comment]
I just submitted to f-droid, and I've realized this app has a gnarly undocumented build process. Once its accepted to f-droid the apk (as well as instructions to build) will be available there.

**Comment by benwaffle** [comment]
sounds good

**Comment by miyachan** [comment]
APKs are now available on f-droid.

https://f-droid.org/repository/browse/?fdid=co.wakarimasen.chanexplorer
