### ISSUE TITLE
A couple of small points

### ISSUE THREAD

**Issue by dalb8** [wakarimasenco/ChanExplorer#2]
I just built the app using the recipe on gitorious. I find it very well designed and implemented. Just wanted to point out a couple of things. 
- Closed threads which normally show a dialog on the web browser only say "There was an error loading the page" at the top and a spinning circle which isn't very helpful.
- I found the film strip in the gallery hard to use, but I guess you'll intend to polish that
- I'd welcome a large size text option
- No indication that it's using SSL
- Regarding the recipe, you don't need to force target=19 alright, it's just that slidingmenu uses google api 14 but that can be changed to android-14 since the maps are removed; it works fine like it is though. You can do this sort of thing with the srclibs/SlidingMenu.txt (since no other app is going to use the maps):

```
-Update Project:Yes
+Srclibs:ActionBarSherlock
+
+Prepare:android update project -p . -t android-14 && rm src/com/slidingmenu/lib/app/SlidingMapActivity.java libs/actionbarsherlock-plugin-maps-4.1.0.jar
```
- I don't see any need for Support-v7 in the code especially since it does the same thing as ActionBarSherlock. 
- The readme says it targets gingerbread; better to say supports gingerbread, since the minsdk is android-10.

**Comment by miyachan** [comment]
1. I'm aware of the error, would appreciate if you opened it in a separate issue.
2. The film strip is badly implemented and can be disabled. I probably won't fix.
3. I believe there are some text size options, if I have this right you want a larger option? (would appreciate if you opened it in a separate issue.)
4. It doesn't use SSL except to post (see /src/co/wakarimasen/chanexplorer/Http.java). I don't particularly have a hard on for SSL, especially for something like 4Chan - and I haven't seen the need for it. If anything I'd prefer to have it off for energy usage and processing sake.
5. The APK won't build without forcing `target=19`
6. Thats been removed in the latest recipe.
7. Wontfix/When I get to it/Make a PR.

**Comment by dalb8** [comment]
Yes, I'll open a new issue.

The app does build without forcing target if you have Google APIs 14 installed, but f-droid deleted those from their config last month.
